import dorsaisImg from './assets/dorsais.png';
import peitoralImg from './assets/peitoral.png';
import trapezioImg from './assets/trapezio.png';
import eretoEspinhaImg from './assets/ereto_espinha.png';
import abdomenImg from './assets/abdomen.png';
import deltoideImg from './assets/deltoide.png';
import bicepsBraquialImg from './assets/biceps_braquial.png';
import tricepsBraquialImg from './assets/triceps_braquial.png';
import quadricepsImg from './assets/quadriceps.png';
import isquiotibiaisImg from './assets/isquiotibiais.png';
import gluteosImg from './assets/gluteos.png';
import panturrilhasImg from './assets/panturrilhas.png';

export const QUIZ_QUESTIONS = [
  // História e Valores da Pratique
  { id: 1, category: 'Pratique', question: 'Qual é o Propósito da Pratique Fitness?', options: ['Ter a mensalidade mais barata do Brasil.', 'Fazer um mundo mais feliz e saudável.', 'Criar os melhores atletas de fisiculturismo.', 'Gastar menos e lucrar mais.'], correctAnswer: 1, explanation: 'O propósito é "Fazer um mundo mais feliz e saudável".' },
  { id: 2, category: 'Pratique', question: 'Qual é a Visão da Pratique Fitness?', options: ['Gastar o mínimo com manutenção.', 'Vender mais planos apenas pela internet.', 'Chegar a 1 milhão de clientes.', 'Crescer apenas no estado de minas gerais.'], correctAnswer: 2, explanation: 'A visão da Pratique é "Chegar a 1 milhão de clientes".' },
  { id: 3, category: 'Pratique', question: 'Qual dos abaixo é um dos principais papéis dos colaboradores da Pratique?', options: ['Conhecer o cliente pelo nome, conhecer o seu objetivo e ensiná-lo corretamente.', 'Focar apenas nos alunos que estão machucados e ignorar os iniciantes.', 'Vender suplementos durante as aulas de musculação.', 'Aguardar os clientes chamarem.'], correctAnswer: 0, explanation: 'Acolher e conhecer o cliente é um dos pilares do atendimento Pratique.' },
  { id: 4, category: 'Pratique', question: 'O que o botão "Abonar" simboliza no sistema de ponto dos colaboradores?', options: ['Abonar atrasos dos alunos.', 'Justificar ausências ou falta de batida no sistema de ponto.', 'Liberar catracas para visitantes.', 'Desconto nas mensalidades.'], correctAnswer: 1, explanation: 'É a funcionalidade de justificar ponto para colaboradores.' },
  { id: 5, category: 'Pratique', question: 'Segundo os valores Pratique, o ambiente das academias deve ser:', options: ['Sério e silencioso sempre.', 'Competitivo e voltado para atletas de elite.', 'Alegre, divertido e acolhedor.', 'Isolado por áreas restritas.'], correctAnswer: 2, explanation: 'A alegria e um ambiente acolhedor fazem parte do propósito "Fazer um mundo mais feliz e saudável".' },

  // Planos Anatômicos
  { id: 6, category: 'Planos Anatômicos', question: 'Qual plano anatômico divide o corpo em lados direito e esquerdo?', options: ['Sagital', 'Frontal', 'Transversal', 'Coronal'], correctAnswer: 0, explanation: 'O Plano Sagital cruza o corpo da frente para trás (movimentos de flexão/extensão).' },
  { id: 7, category: 'Planos Anatômicos', question: 'O exercício "Elevação Lateral" para deltoides ocorre primariamente em qual plano?', options: ['Eixo Longitudinal', 'Frontal', 'Sagital', 'Transversal'], correctAnswer: 1, explanation: 'A Elevação Lateral é abdução, que ocorre no Plano Frontal.' },
  { id: 8, category: 'Planos Anatômicos', question: 'O movimento de Rotação Interna e Externa ocorre em qual plano?', options: ['Frontal', 'Mediano', 'Transversal', 'Sagital'], correctAnswer: 2, explanation: 'Rotações ocorrem no Plano Transversal (Horizontal).' },
  { id: 9, category: 'Planos Anatômicos', question: 'O exercício "Crucifixo Reto" ocorre primariamente em qual plano mecânico do corpo?', options: ['Frontal', 'Sagital', 'Transversal', 'Transversal com eixo antero-posterior'], correctAnswer: 2, explanation: 'O Crucifixo é uma Adução Horizontal, realizada no Plano Transversal.' },
  { id: 10, category: 'Planos Anatômicos', question: 'Exercícios de Agachamento e Leg Press acontecem predominantemente em qual plano?', options: ['Frontal', 'Transversal', 'Sagital', 'Rotacional'], correctAnswer: 2, explanation: 'O Agachamento possui flexão e extensão (plano Sagital).' },
  { id: 11, category: 'Planos Anatômicos', question: 'Plano Coronal é um sinônimo de:', options: ['Plano Sagital', 'Plano Frontal', 'Plano Transversal', 'Plano Axial'], correctAnswer: 1, explanation: 'Coronal refere-se à sutura coronal do crânio, que divide o corpo em frente/costas (Plano Frontal).' },
  { id: 12, category: 'Planos Anatômicos', question: 'O eixo anteroposterior está relacionado diretamente a qual Plano Anatômico?', options: ['Plano Sagital', 'Plano Frontal', 'Plano Transversal', 'Plano Obliquo'], correctAnswer: 1, explanation: 'O eixo anteroposterior atravessa em ângulo reto o plano frontal (ex: movimentos de abdução rotacionam ao redor deste eixo).' },
  { id: 13, category: 'Planos Anatômicos', question: 'Que plano divide o corpo em parte superior (cranial) e parte inferior (caudal)?', options: ['Sagital', 'Frontal', 'Transversal', 'Obliquo'], correctAnswer: 2, explanation: 'O plano transversal divide corpo horizontalmente.' },
  { id: 14, category: 'Planos Anatômicos', question: 'O movimento "Polichinelo" é uma mistura da ação de pernas e braços em qual plano?', options: ['Frontal', 'Sagital', 'Transversal', 'Rotacional'], correctAnswer: 0, explanation: 'Mover braços e pernas para os lados ocorre no plano Frontal.' },
  { id: 15, category: 'Planos Anatômicos', question: 'Rosca direta para bíceps é um movimento em qual plano?', options: ['Transversal', 'Sagital', 'Frontal', 'Diagonal'], correctAnswer: 1, explanation: 'Flexão de cotovelo ocorre estritamente no Plano Sagital.' },

  // Cinesiologia e Biomecânica
  { id: 16, category: 'Cinesiologia', question: 'Durante a execução da Cadeira Extensora, qual movimento a articulação do joelho realiza na fase concêntrica?', options: ['Supinação', 'Dorsiflexão', 'Extensão', 'Flexão'], correctAnswer: 2, explanation: 'Fase concêntrica é quando o músculo vence a carga, na cadeira extensora o joelho estende.' },
  { id: 17, category: 'Cinesiologia', question: 'O músculo que realiza o principal movimento em um exercício é classificado como:', options: ['Agonista', 'Estabilizador', 'Fixador', 'Antagonista'], correctAnswer: 0, explanation: 'Agonista é o principal.' },
  { id: 18, category: 'Cinesiologia', question: 'Qual é o movimento da articulação do cotovelo na Puxada Alta (Lat Pulldown)?', options: ['Abdução', 'Adução', 'Flexão', 'Extensão'], correctAnswer: 2, explanation: 'Ele flete à medida que a barra desce em direção ao peitoral.' },
  { id: 19, category: 'Cinesiologia', question: 'A fase excêntrica de um movimento de Musculação é aquela em que o músculo:', options: ['Acurta (contração concêntrica)', 'Permanece do mesmo tamanho', 'Alonga ou cede contra a resistência', 'Relaxa totalmente'], correctAnswer: 2, explanation: 'Na fase excêntrica o músculo alonga sob tensão freando a carga.' },
  { id: 20, category: 'Cinesiologia', question: 'No supino reto, qual é o papel do Tríceps Braquial?', options: ['Agonista Primário', 'Sinergista (Auxiliar)', 'Antagonista', 'Estabilizador de quadril'], correctAnswer: 1, explanation: 'O Tríceps auxilia na extensão de cotovelo, enquanto o Peitoral Maior é o Agonista do ombro.' },
  { id: 21, category: 'Cinesiologia', question: 'O movimento que afasta a perna da linha mediana do corpo é chamado de:', options: ['Adução', 'Flexão', 'Abdução', 'Rotação'], correctAnswer: 2, explanation: 'Abdução é afastar do eixo central.' },
  { id: 22, category: 'Cinesiologia', question: 'Na cadeira flexora (posterior de coxa), qual é o movimento da articulação do tornozelo se for usar a panturrilha em isometria?', options: ['Flexão Plantar', 'Dorsiflexão', 'Eversão', 'Inversão'], correctAnswer: 0, explanation: 'Flexão plantar aumenta o estímulo se executada em exercícios de panturrilha, porém na flexora mantê-la pode ativar o gastrocnêmio.' },
  { id: 23, category: 'Cinesiologia', question: 'Qual é considerado o músculo antagonista do grupo Quadríceps durante a extensão de joelho?', options: ['Tibial anterior', 'Sartório', 'Gastrocnêmio', 'Isquiotibiais'], correctAnswer: 3, explanation: 'Os isquiotibiais se opõem à ação do quadríceps na articulação do joelho.' },
  { id: 24, category: 'Cinesiologia', question: 'Uma contração muscular isométrica é...', options: ['Quando há variação de comprimento do músculo sem carga', 'Quando o músculo gera força máxima gerando movimento veloz', 'Quando o comprimento não muda enquanto gera tensão', 'Quando a fáscia relaxa'], correctAnswer: 2, explanation: 'Isometria refere-se à tensão sem alteração do arco de movimento.' },
  { id: 25, category: 'Cinesiologia', question: 'Durante um agachamento na subida (extensão do joelho e quadril), a contração dos glúteos e quadríceps é:', options: ['Excêntrica', 'Concêntrica', 'Isométrica', 'Isocinética'], correctAnswer: 1, explanation: 'Subir (vencer a carga) = Contração concêntrica.' },
  { id: 26, category: 'Cinesiologia', question: 'O que o movimento de Dorsiflexão faz?', options: ['Aponta a ponta do pé para o alto.', 'Aponta a ponta do pé para baixo como uma bailarina.', 'Traz o ombro até a orelha.', 'Roda a perna para fora.'], correctAnswer: 0, explanation: 'Dorsiflexão é a ação de levantar os dedos do pé para cima em direção à canela.' },
  { id: 27, category: 'Cinesiologia', question: 'O oposto da Dorsiflexão (apontar dedos para o chão) se chama:', options: ['Eversão', 'Inversão', 'Flexão Plantar', 'Rotação Axial'], correctAnswer: 2, explanation: 'Flexão plantar (como ficar na ponta do pé).' },
  { id: 28, category: 'Cinesiologia', question: 'Eversão no tornozelo é o movimento que:', options: ['Vira a sola do pé para fora (distante do plano mediano).', 'Vira a sola do pé para dentro.', 'Dobra os dedos.', 'Estende os dedos.'], correctAnswer: 0, explanation: 'Eversão gira a planta do pé lateralmente.' },
  { id: 29, category: 'Cinesiologia', question: 'Na rosca concentrada para bíceps, qual articulação deve ser o principal eixo fixo?', options: ['Ombro', 'Cotovelo', 'Punho', 'Radioulnar'], correctAnswer: 1, explanation: 'O cotovelo apoia-se na perna agindo como o pivô, gerando flexão de cotovelo puramente.' },
  { id: 30, category: 'Cinesiologia', question: 'Uma alavanca de Terceira Classe no corpo humano é mais associada à:', options: ['Mecânica onde a Força está entre a Resistência e o Apoio (Eixo).', 'Mecânica onde a Resistência está entre o Apoio e a Força.', 'Mecânica como mover a cabeça no pescoço.', 'Alavanca do Tríceps no cotovelo.'], correctAnswer: 0, explanation: 'Terceira classe (interpotente) = como o bíceps puxando o antebraço. A força puxa o osso entre a carga da mão e a junta do cotovelo.' },
  
  // Músculos
  { id: 31, category: 'Anatomia Muscular', question: 'Qual conjunto é formado por Reto Femoral, Vasto Lateral, Vasto Medial e Vasto Intermédio?', options: ['O Bíceps sural', 'O Quadríceps', 'Os Isquiotibiais', 'Os Glúteos'], correctAnswer: 1, explanation: 'Esses 4 músculos formam a coxa anterior (Quadríceps).', explanationImage: quadricepsImg },
  { id: 32, category: 'Anatomia Muscular', question: 'O Bíceps Braquial possui quantas cabeças/porções?', options: ['Duas (Longa e Curta)', 'Apenas uma', 'Três (Longa, Lateral e Medial)', 'Quatro'], correctAnswer: 0, explanation: 'Bíceps = Bi (Duas) + Ceps (Cabeças).', explanationImage: bicepsBraquialImg },
  { id: 33, category: 'Anatomia Muscular', question: 'Os Isquiotibiais são responsáveis primariamente por qual função no joelho e quadril?', options: ['Levantar os ombros.', 'Extensão do joelho e rotação de tornozelo.', 'Flexão de quadril isoladamente.', 'Flexão do joelho e extensão do quadril.'], correctAnswer: 3, explanation: 'Músculos posteriores da coxa fletem o joelho e ajudam o glúteo estender o quadril.', explanationImage: isquiotibiaisImg },
  { id: 34, category: 'Anatomia Muscular', question: 'O Tríceps Sural é composto basicamente por:', options: ['Fibular longo e Tibial.', 'Sartório.', 'Gastrocnêmio e Sóleo.', 'Oblíquos.'], correctAnswer: 2, explanation: 'O tríceps sural é a panturrilha (Gastrocnêmios + Sóleo).', explanationImage: panturrilhasImg },
  { id: 35, category: 'Anatomia Muscular', question: 'Na execução do Levantamento Terra, o Ereto Espinhal atua principalmente como:', options: ['Relaxado totalmente.', 'Flexor de cotovelo.', 'Estabilizador e extensor da coluna vertebral.', 'Adutor da escápula.'], correctAnswer: 2, explanation: 'Contrai fortemente em isometria para manter a coluna ereta.', explanationImage: eretoEspinhaImg },
  { id: 36, category: 'Anatomia Muscular', question: 'Qual é o maior músculo do corpo (em volume) e principal extensor do quadril?', options: ['Latíssimo do dorso', 'Glúteo Máximo', 'Quadríceps', 'Peitoral Maior'], correctAnswer: 1, explanation: 'O Glúteo Máximo tem força e tamanho consideráveis para extensão e abdução.', explanationImage: gluteosImg },
  { id: 37, category: 'Anatomia Muscular', question: 'O músculo Latíssimo do Dorso é popularmente conhecido como:', options: ['Trapézio', 'Bíceps', 'Asa das costas / Grande dorsal', 'Deltóide Posterior'], correctAnswer: 2, explanation: 'Devido ao seu leque lateral grande.', explanationImage: dorsaisImg },
  { id: 38, category: 'Anatomia Muscular', question: 'O grupamento do Peitoral é subdividido anatomicamente em:', options: ['Porção Ulnar e Radial.', 'Peitoral Maior e Peitoral Menor.', 'Anterior, Posterior e Transverso.', 'Vasto e Reto.'], correctAnswer: 1, explanation: 'Temos o Peitoral Maior (superficial e grande) e o Menor (profundo).', explanationImage: peitoralImg },
  { id: 39, category: 'Anatomia Muscular', question: 'Músculos abdominais profundos responsáveis por funcionar como um cinto (cinta modeladora natural) do tronco:', options: ['Reto do Abdômen', 'Transverso do Abdômen', 'Eretores da espinha', 'Serrátil anterior'], correctAnswer: 1, explanation: 'O Transverso do Abdômen envolve como uma cinta e quando fortalecido segura a linha da cintura estabilizando o core.', explanationImage: abdomenImg },
  { id: 40, category: 'Anatomia Muscular', question: 'O Trapézio é comumente dividido em:', options: ['Anterior e Posterior', 'Superior, Médio e Inferior', 'Cabeça longa e curta', 'Lateral e Medial'], correctAnswer: 1, explanation: 'As fibras trapézio descendem, vão horizontais e ascendem (superior/médio/inferior).', explanationImage: trapezioImg },
  
  // Mistos Extra (Exercícios e Aparelhos)
  { id: 41, category: 'Exercícios', question: 'No Aparelho Peck Deck (Voador), o músculo motor principal é:', options: ['Trapézio Superior', 'Peitoral Maior', 'Latíssimo do Dorso', 'Tríceps Braquial'], correctAnswer: 1, explanation: 'O movimento cruzado da frente ativa os peitorais (Adução horizontal de ombros).', explanationImage: peitoralImg },
  { id: 42, category: 'Exercícios', question: 'Exercício "Stiff" enfatiza principalmente trabalhar qual cadeia muscular?', options: ['Cadeia Anterior da Coxa', 'Cadeia Posterior (Isquiotibiais e Glúteo)', 'Banda iliotibial', 'Deltoides'], correctAnswer: 1, explanation: 'Por focar bastante em extensão de quadril o Stiff alonga fortemente cadeia posterior.', explanationImage: isquiotibiaisImg },
  { id: 43, category: 'Cinesiologia', question: 'Qual ação o Bíceps Braquial faz além de fletir o cotovelo?', options: ['Pronar o antebraço', 'Supinar o antebraço (virar a palma para cima)', 'Extensão do ombro', 'Rotação lateral no úmero'], correctAnswer: 1, explanation: 'O Bíceps Braquial é um poderoso supinador do rádio (ante-braço).', explanationImage: bicepsBraquialImg },
  { id: 44, category: 'Anatomia Muscular', question: 'O músculo Serrátil Anterior é conhecido assim porque:', options: ['Puxa como serrote o tendão patelar', 'Apresenta formato de borda de faca (serras) perto das costelas laterais', 'Prende a espinha', 'Sobra após a remoção da clavícula'], correctAnswer: 1, explanation: 'Localizado sob as axilas parecendo dentes de serra, muito visto em boxeadores.' },
  { id: 45, category: 'Anatomia Muscular', question: 'Se estou fazendo remada com pegada bem fechada neutra (Triângulo), atinjo perfeitamente qual porção grande das costas?', options: ['Latíssimo do dorso', 'Infraespinhoso', 'Bíceps longo', 'Trapézio Superior isolado'], correctAnswer: 0, explanation: 'A tração em linha anteroposterior junto ao corpo enfatiza latíssimo dorso e romboides.', explanationImage: dorsaisImg },
  { id: 46, category: 'Cinesiologia', question: 'Qual é um risco biomecânico em um Agachamento Profundo com a coluna retrovertida (hip print pelvico, "butt wink")?', options: ['Aumento excessivo do quadríceps', 'Esmagamento ou protusão/herniação dos discos intervertebrais lombares', 'Ruptura no ligamento colateral lateral do joelho', 'Cãibra imediata na panturrilha'], correctAnswer: 1, explanation: 'O arredondamento da lombar transfere a carga direto para o disco causando risco discal.', explanationGif: 'https://fitcron.com/wp-content/uploads/2021/04/00441301-Barbell-Good-Morning_Thighs_720.gif' },
  { id: 47, category: 'Exercícios', question: 'Cadeira Abdutora serve para:', options: ['Ativação isolada de Quadríceps', 'Ativação direcionada aos Glúteos Médio/Mínimo (Lateral do glúteo)', 'Tonificar Adutores da perna interna', 'Descansar o tibial posterior'], correctAnswer: 1, explanation: 'Abdução do quadril = trabalho intenso em glúteo médio.', explanationImage: gluteosImg },
  { id: 48, category: 'Anatomia Muscular', question: 'Deltoides são os músculos protetores envoltórios de qual articulação principal?', options: ['Quadril', 'Ombro (Glenoumeral)', 'Cotovelo', 'Arco Costal'], correctAnswer: 1, explanation: 'Ombro. O deltoide é como uma "ombreira".', explanationImage: deltoideImg },
  { id: 49, category: 'Cinesiologia', question: 'O movimento de empurrar verticalmente acima da cabeça (Desenvolvimento), usa predominantemente:', options: ['Deltoides parte anterior/média e Tríceps Braquial', 'Peitoral e Bíceps', 'Glúteo Médio e Trapézio inferior', 'Tibial anterior.'], correctAnswer: 0, explanation: 'Elevação frontal/lateral vertical utiliza fortemente Deltoides e o movimento de cotovelo usa os tríceps.' },
  { id: 50, category: 'Pratique', question: 'Na Pratique, um pilar fundamental da retenção é?', options: ['Desestimular clientes idosos', 'Acompanhamento constante, empatia e montagem correta de séries (Atendimento)', 'Ter todas as esteiras equipadas com Netflix, apenas.', 'Não permitir o uso do sanitário.'], correctAnswer: 1, explanation: 'Relacionamento com o cliente garante a manutenção dele!' },
  
  // Extra para chegar em um banco confortável de dados para sorteio.  
  { id: 51, category: 'Anatomia Muscular', question: 'Quais músculos compõem o manguito rotador do ombro?', options: ['Supraspinhal, Infraespinhal, Redondo Menor e Subescapular', 'Bíceps, Tríceps, Deltoide, Coracobraquial', 'Peitoral maior, menor, Serrátil e Trapézio', 'Gastrocnêmio e Flexores plantares'], correctAnswer: 0, explanation: 'Estes quatro são essenciais para estabilizar e rodar o ombro.' },
  { id: 52, category: 'Anatomia Muscular', question: 'O que é o músculo Rombóide e onde se localiza?', options: ['Nas extremidades dos dedos (unhas)', 'No peito', 'Nas costas, deitado abaixo e entre o Trapézio fixando a Escápula', 'Na parte anterior da perna'], correctAnswer: 2, explanation: 'Os romboides (maior, menor) retraem e unem as escápulas contra a coluna.' },
  { id: 53, category: 'Exercícios', question: 'Qual é considerado o rei dos exercícios por mobilizar quase todo o corpo num só gesto?', options: ['Elevação plantar', 'Cadeira Abdutora', 'Levantamento Terra (Deadlift)', 'Encolhimento de Ombros'], correctAnswer: 2, explanation: 'Usa a cadeia posterior inteira, antebraço (pegada), abdominais, ombros para estabilizar.' },
  { id: 54, category: 'Planos Anatômicos', question: 'Os abdominais laterais e oblíquos atuam muito fortemente para impedir, ou realizar, o movimento no plano:', options: ['Rotacional / Transversal (torções de tronco)', 'Frontal apenas', 'Eixo radial puro', 'Cranial puro'], correctAnswer: 0, explanation: 'Enquanto o reto encolhe de frente (sagital), oblíquos giram a caixa torácica no bloco transversal.' },
  { id: 55, category: 'Exercícios', question: 'O agachamento Búlgaro é famoso por ser um movimento do tipo:', options: ['Isolado para Glúteo máximo unicamente', 'Unilateral / Assimetricamente dominante para focar mais profundamente na estrutura inferior (Coxas/Glúteos)', 'Exclusivo focado para panturrilha', 'Pliométrico'], correctAnswer: 1, explanation: 'Por estabilizar numa perna só, recruta intensamente glúteos de estabilização e quadríceps da perna de apoio.' },
  { id: 56, category: 'Anatomia Muscular', question: 'Qual é a função primordial do Músculo Sartório?', options: ['Estender o ombro', 'Flexionar os dedos do pé', 'O mais longo do corpo cruza coxa - Flete Coxa e Flete/gira Joelho int.', 'Mastigação'], correctAnswer: 2, explanation: 'Sartório é o grandão superficial em S na perna usado pra "bater o tornozelo na bola de chapa" - flexiona e gira lateral o quadril.' },
  
  // Perguntas Analíticas com Imagem
  { id: 57, category: 'Análise Biomecânica', question: 'Analisando o movimento na imagem, qual é o grupamento muscular predominante exercitado (Agonista)?', gif: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif', options: ['Dorsais e lombar', 'Peitoral Maior e Tríceps Braquial', 'Isquiotibiais e Glúteos', 'Bíceps e Antebraço'], correctAnswer: 1, explanation: 'A ilustração é do Supino Reto, movimento basista de "empurrar" que trabalha inteiramente o grupamento do Peitoral, com apoio forte dos Deltoides anteriores e Tríceps.' },
  { id: 58, category: 'Análise Biomecânica', question: 'Observe a execução. Qual plano anatômico e movimento principal estão sendo realizados pelo quadril e pelos joelhos mecânicos?', gif: 'https://www.hipertrofia.org/blog/wp-content/uploads/2023/07/bodyweight-squat.gif', options: ['Plano Transversal / Rotação Externa', 'Plano Frontal / Abdução de pernas', 'Plano Sagital / Flexão e Extensão', 'Eixo Longitudinal (Puro)'], correctAnswer: 2, explanation: 'O gif mostra o Agachamento (Squat), exercício clássico inteiramente no Plano Sagital que flexiona (desce) e estende (sobe) ativando quadríceps e glúteos.' },
  { id: 59, category: 'Cinesiologia e Movimento', question: 'No aparelho mostrado, qual o principal responsável por puxar (fletir) e tracionar o peso da alavanca?', gif: 'https://www.mundoboaforma.com.br/wp-content/uploads/2021/04/pernas-flexao-de-pernas-na-maquina.gif', options: ['Glúteos e adutores', 'Tríceps Surais (Panturrilhas)', 'Quadríceps femoral', 'Isquiotibiais (Posterior de Coxa)'], correctAnswer: 3, explanation: 'O gif exibe a famosa Mesa Flexora, e a flexão de perna atinge em cheio os três músculos que formam os isquiotibiais.' },
  { id: 60, category: 'Análise Biomecânica', question: 'Qual é a ação do tríceps braquial observada neste tradicional exercício feito em polia?', gif: 'https://media.tenor.com/mbebKudZjxYAAAAM/tr%C3%ADceps-pulley.gif', options: ['Elevação rotacional de ombro', 'Dorsiflexão manual', 'Extensão de cotovelo concêntrica na descida', 'Isometria de trapézio'], correctAnswer: 2, explanation: 'O Tríceps Corda/Pulley utiliza justamente a expansão de cotovelo, empurrando a carga até alinhar o braço no plano focal.' },
  { id: 61, category: 'Cinesiologia e Movimento', question: 'O movimento do puxador (Pulldown) aciona qual plano e o seu motor predominante é qual músculo?', gif: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif', options: ['Plano Frontal - Latíssimo do Dorso ("Asas")', 'Plano Sagital - Peitoral Maior', 'Plano Transversal - Sustentação Paravertebral', 'Plano Obliquo - Glúteos'], correctAnswer: 0, explanation: 'A Puxada Alta frontal (pegada aberta) puxa os cotovelos num plano frontal descendo lateralmente aos flancos do corpo contraindo dorsais.' },
  { id: 62, category: 'Análise Biomecânica', question: 'A elevação dos pesos usando os ombros acontece dentro de qual plano funcional (divisão do corpo) e trabalha qual região?', gif: 'https://www.mundoboaforma.com.br/wp-content/uploads/2020/12/ombros-elevacao-lateral-de-ombros-com-halteres.gif', options: ['Plano Sagital focando Deltoide Anterior', 'Plano Frontal provocando Abdução para Deltoide Medial', 'Plano Transversal - Deltóide Posterior e Costas largas', 'Isometria do Peitoral'], correctAnswer: 1, explanation: 'A temida Elevação Lateral movimenta os braços afastando da linha média. Como correm lateralmente ao corpo, a secção cortada visual desse movimento é a do Plano Frontal.' },
];
